frase=input('Digite uma frase: ')
minusculo=frase.lower()
numero=minusculo.count('a')
print('A sua frase contem {} letras a'.format(numero))
primeiro=minusculo.find('a')
primeira=int(primeiro)
print('a primeira frase contem a letra A na posição {}'.format(primeira+1))
ultimo=minusculo.rfind('a')
ultima=int(ultimo)
print('A ultima letra A que aparece na frase está na {} posição'.format(ultima-1))