coisa=input('Digite algo :')
print(coisa)
print(type(coisa))
print(coisa.isalnum())
print(coisa.isalpha())
print(format(coisa.islower()))
print(coisa.isdecimal())
print(coisa.isdigit())
print(coisa.isnumeric())
print(coisa.isupper())
print(coisa.isspace())